import { put } from "@vercel/blob";
import { getSql } from "@/db";
import { requireUser } from "@/lib/access";

const seeds=[
  ["seed-kbank","kbank 0169-0669 00023 สรุป.pdf","KBANK","ม.ค.–มิ.ย. 2569","2026-01-01","2026-06-30","application/pdf"],
  ["seed-bbl","bbl 0169-0669.pdf","BBL","ม.ค.–มิ.ย. 2569","2026-01-01","2026-06-30","application/pdf"],
  ["seed-ktb-pdf","ktb 0169-0669 0503508000023สรุป.pdf","KTB","ม.ค.–มิ.ย. 2569","2026-01-01","2026-06-30","application/pdf"],
  ["seed-ktb-xls","Historical_SSKBA04973.xls","KTB","ม.ค.–มิ.ย. 2569","2026-01-01","2026-06-30","application/vnd.ms-excel"],
  ["seed-ktb-xls-2","Historical_SSKBA04973_XXX-X-XX125-8_20260803 2.xls","KTB","ม.ค.–มิ.ย. 2569","2026-01-01","2026-06-30","application/vnd.ms-excel"],
  ["seed-kbank-july","KBNAK 0769 00023.pdf","KBANK","ก.ค. 2569","2026-07-01","2026-07-31","application/pdf"],
  ["seed-bbl-july","BBL0769.pdf","BBL","ก.ค. 2569","2026-07-01","2026-07-31","application/pdf"],
  ["seed-ktb-july","KTB 0769 0503508000023.xls","KTB","ก.ค. 2569","2026-07-01","2026-07-31","application/vnd.ms-excel"],
] as const;
async function ensure(){const sql=getSql();await sql.query(`CREATE TABLE IF NOT EXISTS evidence_files(id text PRIMARY KEY,file_name text NOT NULL,storage_key text,bank text NOT NULL,period text NOT NULL,statement_from date,statement_to date,content_type text NOT NULL,size_bytes bigint NOT NULL DEFAULT 0,status text NOT NULL DEFAULT 'รอตรวจสอบ',source text NOT NULL DEFAULT 'upload',processing_status text NOT NULL DEFAULT 'รอประมวลผล',processed_at timestamptz,detected_transactions integer NOT NULL DEFAULT 0,page_count integer NOT NULL DEFAULT 0,uploaded_at timestamptz NOT NULL DEFAULT now())`);await sql.query(`CREATE TABLE IF NOT EXISTS dashboard_audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),action text NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,summary text NOT NULL,before_json text,after_json text,actor text NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`);for(const f of seeds)await sql.query(`INSERT INTO evidence_files(id,file_name,bank,period,statement_from,statement_to,content_type,status,source,processing_status,processed_at) VALUES($1,$2,$3,$4,$5,$6,$7,'นำเข้ารายงานแล้ว','existing','นำเข้า Dashboard แล้ว',now()) ON CONFLICT(id) DO NOTHING`,[...f])}
export async function GET(){try{await requireUser();await ensure();return Response.json({files:await getSql().query(`SELECT * FROM evidence_files ORDER BY uploaded_at DESC,file_name`)})}catch(e){return Response.json({error:e instanceof Error?e.message:"อ่านทะเบียนไฟล์ไม่สำเร็จ"},{status:500})}}
export async function POST(request:Request){try{const actor=await requireUser();await ensure();const form=await request.formData(),file=form.get("file"),bank=String(form.get("bank")||"OTHER").toUpperCase(),from=String(form.get("statement_from")||""),to=String(form.get("statement_to")||"");if(!(file instanceof File)||!file.size)return Response.json({error:"กรุณาเลือกไฟล์"},{status:400});if(file.size>4*1024*1024)return Response.json({error:"ระบบออนไลน์รองรับไฟล์ไม่เกิน 4 MB ต่อครั้ง"},{status:400});if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)return Response.json({error:"ช่วงวันที่ไม่ถูกต้อง"},{status:400});const id=crypto.randomUUID(),text=String(form.get("extracted_text")||"").slice(0,1_000_000),pages=Math.max(0,Number(form.get("page_count")||0)),pattern=bank==="KBANK"?/\b\d{2}-\d{2}-\d{2}\s+\d{2}:\d{2}\b/g:/\b\d{2}\/\d{2}\/20\d{2}/g,matches=text.match(pattern)||[],detected=bank==="BBL"?Math.floor(matches.length/2):matches.length;let storageKey:string|null=null;if(process.env.BLOB_READ_WRITE_TOKEN){const blob=await put(`evidence/${id}/${file.name}`,file,{access:"private",addRandomSuffix:false});storageKey=blob.url}const processing=text?`อ่านไฟล์แล้ว · ตรวจพบประมาณ ${detected} รายการ`:"รับทะเบียนไฟล์แล้ว · รอประมวลผล";const sql=getSql();await sql.query(`INSERT INTO evidence_files(id,file_name,storage_key,bank,period,statement_from,statement_to,content_type,size_bytes,status,source,processing_status,processed_at,detected_transactions,page_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'upload',$11,now(),$12,$13)`,[id,file.name,storageKey,bank,`${from} ถึง ${to}`,from,to,file.type||"application/octet-stream",file.size,storageKey?"เก็บไฟล์แล้ว":"บันทึกทะเบียนแล้ว-รอเชื่อมพื้นที่ไฟล์",processing,detected,pages]);await sql.query(`INSERT INTO dashboard_audit_logs(action,entity_type,entity_id,summary,after_json,actor) VALUES('UPLOAD','evidence_file',$1,$2,$3,$4)`,[id,`อัปโหลด ${bank}: ${file.name}`,JSON.stringify({bank,from,to,detected,pages,stored:Boolean(storageKey)}),actor.email]);return Response.json({ok:true,id,processingStatus:processing,detectedTransactions:detected,pageCount:pages},{status:201})}catch(e){return Response.json({error:e instanceof Error?e.message:"อัปโหลดไม่สำเร็จ"},{status:500})}}
